export const REQUEST = "REQUEST";

export const GET_ALL_DOGS_SUCCESS = "GET_ALL_DOGS_SUCCESS";
export const GET_ALL_DOGS_FAILURE = "GET_ALL_DOGS_FAILURE";

export const GET_DOG_BY_NAME_SUCCESS = "GET_DOG_BY_NAME_SUCCESS";
export const GET_DOG_BY_NAME_FAILURE = "GET_DOG_BY_NAME_FAILURE";

export const CREATE_DOG_SUCCESS = "CREATE_DOG_REQUEST";
export const CREATE_DOG_FAILURE = "CREATE_DOG_REQUEST";

export const CLEAR_FILTERED_DOGS = "CLEAR_FILTERED_DOGS";

export const GET_ALL_TEMPERAMENTS_SUCCESS = "GET_ALL_TEMPERAMENTS_SUCCESS";
export const GET_ALL_TEMPERAMENTS_FAILURE = "GET_ALL_TEMPERAMENTS_FAILURE";

export const SORT_DOGS_AZ = "SORT_DOGS_AZ";
export const SORT_DOGS_ZA = "SORT_DOGS_ZA";

export const SORT_DOGS_BY_WEIGHT_ASC = "SORT_DOGS_BY_WEIGHT_ASC";
export const SORT_DOGS_BY_WEIGHT_DES = "SORT_DOGS_BY_WEIGHT_DES";

export const FILTER_DOGS_DB = "FILTER_DOGS_DB";
export const FILTER_DOGS_API = "FILTER_DOGS_API";

export const FILTER_DOGS_BY_TEMP = "FILTER_DOGS_BY_TEMP";
export const DELETE_DOG = "DELETE_DOG";
